akira/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve

from django.contrib.auth.decorators import login_required
from django.urls.conf import re_path
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('akira_apps.authentication.urls')),
    path('super_admin/', include('akira_apps.super_admin.urls')),
    path('staff/', include('akira_apps.staff.urls')),
    path('student/', include('akira_apps.student.urls')),
    path('academic_registration/', include('akira_apps.academic_registration.urls')),
    path('academic/', include('akira_apps.academic.urls')),
    path('accounts/', include('akira_apps.accounts.urls')),
    path('course/', include('akira_apps.course.urls')),
    path('specialization/', include('akira_apps.specialization.urls')),
    path('shigen/', include('akira_apps.shigen.urls')),
    path('adops/', include('akira_apps.adops.urls')),
    path('', include('akira_apps.URLShortener.urls')),

    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),

    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml',TemplateView.as_view(template_name="sitemap.xml", content_type="application/xml")),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
]

akira_apps/staff/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('hod_dashboard/', views.hod_dashboard, name="hod_dashboard"),
    path('staff_dashboard/', views.staff_dashboard, name="staff_dashboard"),
    path('applicant_dashboard/', views.applicant_dashboard, name="applicant_dashboard"),
    path('manage_staff/', views.manage_staff, name = 'manage_staff'),
    path('bulk_upload_staffs_save/', views.bulk_upload_staffs_save, name = 'bulk_upload_staffs_save'),
    path('staff_info_csv/', views.staff_info_csv, name = 'staff_info_csv'),
    path('add_staff/', views.add_staff, name = 'add_staff'),
    path('view_staff/<staff_username>/', views.view_staff, name = 'view_staff'),
    path('edit_staff/<staff_username>/', views.edit_staff, name = 'edit_staff'),
    
    path('staff_enroll_course/<course_id>/', views.staff_enroll_course, name="staff_enroll_course"),
    path('staff_unenroll_course/<staff_enroll_course_id>/', views.staff_unenroll_course, name="staff_unenroll_course"),

    path('student_enroll_course/<course_id>/', views.student_enroll_course, name="student_enroll_course"),

    path('add_student/', views.add_student, name = 'add_student'),
]

akira_apps/course/models.py
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver

import uuid
import os

from akira_apps.academic.models import (Semester, Branch)
from akira_apps.specialization.models import (SpecializationsMC)

class CourseMC(models.Model):
    COURSE_TYPE = [
        ("", "Course Type"),
        ("Professional Elective", "Professional Elective"),
        ("Foreign Language Elective", "Foreign Language Elective"),
        ("Open Elective", "Open Elective"),
        ("Science Elective", "Science Elective"),
        ("NDY", "NDY"),
    ]
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    code = models.CharField(max_length = 100, unique = True)
    name = models.CharField(max_length = 100, unique = True)
    desc = models.TextField(max_length = 500)
    course_coordinator = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    branch = branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.SET_NULL, blank=True, null=True)
    specialization = models.ForeignKey(SpecializationsMC, on_delete=models.SET_NULL, blank=True, null=True)
    type = models.CharField(max_length = 50, choices = COURSE_TYPE, default=1)
    pre_requisite = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.code, self.name)

class CourseExtraFields(models.Model):
    FIELD_TYPE = [
        ("", "Select Field type"),
        ("text", "Short text"),
        ("textarea", "Long text"),
        ("number", "Number"),
    ]
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    course = models.ForeignKey(CourseMC, on_delete=models.CASCADE)
    field_name = models.CharField(max_length = 100)
    field_type = models.CharField(max_length = 100, choices = FIELD_TYPE, default="")
    field_value = models.TextField(max_length = 50000)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.course, self.field_name)

class CourseOfferingType(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    course = models.ForeignKey(CourseMC, on_delete=models.CASCADE)
    name = models.CharField(max_length = 40)
    l = models.IntegerField(default=0)
    t = models.IntegerField(default=0)
    p = models.IntegerField(default=0)
    s = models.IntegerField(default=0)
    credits = models.IntegerField(default=0)

    def __str__(self):
        return '%s - %s' % (self.course, self.name)

class CourseCOTExtraFields(models.Model):
    FIELD_TYPE = [
        ("", "Select Field type"),
        ("text", "Short text"),
        ("textarea", "Long text"),
        ("number", "Number"),
    ]
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    course = models.ForeignKey(CourseOfferingType, on_delete=models.CASCADE)
    field_name = models.CharField(max_length = 100)
    field_type = models.CharField(max_length = 100, choices = FIELD_TYPE, default="")
    field_value = models.TextField(max_length = 50000)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.course, self.field_name)

class CourseFiles(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    course = models.ForeignKey(CourseMC, on_delete=models.CASCADE)
    course_files = models.FileField(upload_to='Course_Files/', blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.course, self.course_files)

@receiver(models.signals.post_delete, sender=CourseFiles)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.course_files:
        if os.path.isfile(instance.course_files.path):
            try:
                os.remove(instance.course_files.path)
            except Exception:
                os.unlink(instance.course_files.path)

class CourseComponent(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    course = models.ForeignKey(CourseMC, on_delete=models.CASCADE)
    name = models.CharField(max_length = 100)
    desc = models.TextField(max_length = 500, null=True, blank=True)

    def __str__(self):
        return '%s - %s' % (self.course, self.name)

class CourseSubComponent(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    component = models.ForeignKey(CourseComponent, on_delete=models.CASCADE)
    name = models.CharField(max_length = 100)
    desc = models.TextField(max_length = 500, null=True, blank=True)

    def __str__(self):
        return '%s - %s' % (self.course, self.name)

class CourseTask(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    sub_component = models.ForeignKey(CourseSubComponent, on_delete=models.CASCADE)
    question = models.TextField(max_length = 500)
    answer = models.ForeignKey('TaskAnswer', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return '%s' % (self.question)

class TaskAnswer(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(CourseTask, on_delete=models.CASCADE)
    answer = models.FileField(upload_to='TaskAnswerFiles/')

    def __str__(self):
        return '%s - %s' % (self.user, self.answer) 

akira_apps/staff/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

import uuid

from akira_apps.academic.models import (Branch)

GENDER_CHOICES = [
    ("", "Select Gender"),
    ("Male", "Male"),
    ("Female", "Female"),
]

BLOOD_GROUP_CHOICES = [
    ("","Blood Group"),
    ("A+","A+"),
    ("A-","A-"),
    ("B+","B+"),
    ("B-","B-"),
    ("O+","O+"),
    ("O-","O-"),
    ("AB+","AB+"),
    ("AB-","AB-"),
]

MOTHER_TOUNGE_CHOICES = [
    ("","Mother Tounge"),
    ("Hindi","Hindi"),
    ("English","English"),
    ("Bengali","Bengali"),
    ("Marathi","Marathi"),
    ("Telugu","Telugu"),
    ("Tamil","Tamil"),
    ("Gujarati","Gujarati"),
    ("Urdu","Urdu"),
    ("Kannada","Kannada"),
    ("Odia","Odia"),
    ("Malayalam","Malayalam"),
    ("Punjabi","Punjabi"),
]

Name_Prefix_Choices = [
    ("","Select Name Prefix"),
    ("Dean","University Dean"),
    ("Dr","Doctor (Medical or Educator)"),
    ("Hon","Honorable"),
    ("Mr","Mister"),
    ("Mrs","Married Woman"),
    ("Ms","Single/Unmarried Women"),
    ("Prof","Professor"),
]

class Staff(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    user = models.OneToOneField(User, unique=True, on_delete = models.CASCADE)
    name_prefix = models.CharField(max_length = 35, choices = Name_Prefix_Choices, default=1)
    gender = models.CharField(max_length=14, choices = GENDER_CHOICES, default=1)
    date_of_birth = models.DateField()
    blood_group = models.CharField(max_length=18, choices = BLOOD_GROUP_CHOICES, default=1)
    phone = models.CharField(max_length = 15)
    door_no = models.CharField(max_length=10)
    zip_code = models.IntegerField()
    city = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    photo = models.ImageField(null=True, blank=True, upload_to='staff_photos/', validators=[FileExtensionValidator(['jpg', 'png', 'jpeg'])])
    branch = models.ForeignKey(Branch, on_delete = models.DO_NOTHING, blank = True, null = True)
    about = models.TextField(max_length=500, null=True, blank=True)
    skills = models.ManyToManyField('Skills', blank = True)
    resume = models.FileField(upload_to ='staff_resumes/', validators=[FileExtensionValidator(['pdf'])], blank = True, null = True)

    def __str__(self):
        return '%s %s %s' % (self.user, self.user.first_name.title(), self.user.last_name.title())
    
    class Meta:
        ordering = ["user__first_name"]

class Skills(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    name = models.CharField(max_length = 50, unique=True)

    def __str__(self):
        return self.name

# class UserExtraFields(models.Model):
#     id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
#     staffMC = models.ForeignKey(Staff, on_delete = models.CASCADE)
#     field_name = models.CharField(max_length = 100)
#     field_value = models.TextField(max_length=500)

#     def __str__(self):
#         return '%s' % (self.field_name)

akira_apps/staff/templates/staff/hod_templates/courses_templates/create_courses.html
{% extends 'side_panel-navbar_dashboard.html' %}
{% load static %}

{% block content %}

<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

<form action="{% url 'save_created_course' %}" method="POST">
    {% csrf_token %}
    <label for="id_course_code">Course Code</label> 
    <input type="text" name="course_code" maxlength="100" id="id_course_code" required>
    <br>
    <label for="id_course_name">Course Name</label>
    <input type="text" name="course_name" maxlength="100" id="id_course_name" required>
    <br>
    <label for="id_course_short_info">Course Short Info</label>
    <textarea name="course_short_info" cols="40" rows="10" maxlength="500" id="id_course_short_info" required></textarea>
    <br>
    <label for="id_course_wywl">What you will learn</label>
    <textarea name="course_wywl" cols="40" rows="10" maxlength="500" id="id_course_wywl" required></textarea>
    <br>
    <label for="id_course_sywg">Skill You Will Gain</label>
    <textarea name="course_sywg" cols="40" rows="10" maxlength="500" id="id_course_sywg" required></textarea>
    <br>
    <label for="id_course_desc">Course Description</label>
    <div class="django-ckeditor-widget" data-field-id="id_course_desc" style="display: inline-block;">
        <textarea cols="40" id="id_course_desc" name="course_desc" rows="10" data-processed="0" 
                data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: 
                                [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], 
                                &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, 
                                &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, 
                                &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], 
                                [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], 
                                [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], 
                                [&quot;Source&quot;]], &quot;toolbar&quot;: [[&quot;Format&quot;, &quot;Bold&quot;, 
                                &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;], [&quot;NumberedList&quot;, 
                                &quot;BulletedList&quot;, &quot;Indent&quot;, &quot;Outdent&quot;, &quot;JustifyLeft&quot;, 
                                &quot;JustifyCenter&quot;, &quot;JustifyRight&quot;, &quot;JustifyBlock&quot;], 
                                [&quot;Image&quot;, &quot;Table&quot;, &quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;, 
                                &quot;SectionLink&quot;, &quot;Subscript&quot;, &quot;Superscript&quot;], [&quot;Undo&quot;, 
                                &quot;Redo&quot;], [&quot;Maximize&quot;]], &quot;height&quot;: 291, &quot;width&quot;: 
                                &quot;auto&quot;, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, 
                                &quot;filebrowserUploadUrl&quot;: &quot;/ckeditor/upload/&quot;, &quot;filebrowserBrowseUrl&quot;: 
                                &quot;/ckeditor/browse/&quot;, &quot;language&quot;: &quot;en-us&quot;}" 
                data-external-plugin-resources="[]" data-id="id_course_desc" data-type="ckeditortype" required>
        </textarea>
    </div>
    <br>
    <label for="id_course_coordinator">Course Co-Ordinator</label>
    <select name="course_coordinator" id="id_course_coordinator" required>
        {% for i in course_coordinator_list %}
        <option value="{{ i.id }}" selected> {{ i }} </option>
        {% endfor %}
    </select>
    <br>
    <label for="id_branch">Branch</label>
    <select name="branch" id="id_branch" required>
        {% for x,y in branch_list.fields.branch.choices %}
            <option value="{{ x }}">{{ y }}</option>
        {% endfor %}
    </select>
    <br>
    <label for="id_semester">Semester</label>
    <select name="semester" id="id_semester" required>
        {% for i in semester_list %}
        <option value="{{ i.id }}" selected> {{ i }} </option>
        {% endfor %}
    </select>
    <br>
    <input type="submit">
</form>

{% endblock %}

akira_apps/staff/templates/staff/hod_templates/courses_templates/edit_course.html
{% extends 'side_panel-navbar_dashboard.html' %}
{% load static %}

{% block content %}

<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

<form action="{% url 'save_edit_course' course.id %}" method="POST">
    {% csrf_token %}
    <label for="id_course_code">Course Code</label> 
    <input type="text" name="course_code" maxlength="100" value="{{ course.course_code }}" id="id_course_code" required>
    <br>
    <label for="id_course_name">Course Name</label>
    <input type="text" name="course_name" maxlength="100" value="{{ course.course_name }}" id="id_course_name" required>
    <br>
    <label for="id_course_short_info">Course Short Info</label>
    <textarea name="course_short_info" cols="40" rows="10" maxlength="500" id="id_course_short_info" required>{{ course.course_short_info }}</textarea>
    <br>
    <label for="id_course_wywl">What you will learn</label>
    <textarea name="course_wywl" cols="40" rows="10" maxlength="500" id="id_course_wywl" required>{{ course.course_wywl }}</textarea>
    <br>
    <label for="id_course_sywg">Skill You Will Gain</label>
    <textarea name="course_sywg" cols="40" rows="10" maxlength="500" id="id_course_sywg" required>{{ course.course_sywg }}</textarea>
    <br>
    <label for="id_course_desc">Course Description</label>
    <div class="django-ckeditor-widget" data-field-id="id_course_desc" style="display: inline-block;">
        <textarea cols="40" id="id_course_desc" name="course_desc" rows="10" data-processed="0" 
                data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: 
                                [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], 
                                &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, 
                                &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, 
                                &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], 
                                [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], 
                                [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], 
                                [&quot;Source&quot;]], &quot;toolbar&quot;: [[&quot;Format&quot;, &quot;Bold&quot;, 
                                &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;], [&quot;NumberedList&quot;, 
                                &quot;BulletedList&quot;, &quot;Indent&quot;, &quot;Outdent&quot;, &quot;JustifyLeft&quot;, 
                                &quot;JustifyCenter&quot;, &quot;JustifyRight&quot;, &quot;JustifyBlock&quot;], 
                                [&quot;Image&quot;, &quot;Table&quot;, &quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;, 
                                &quot;SectionLink&quot;, &quot;Subscript&quot;, &quot;Superscript&quot;], [&quot;Undo&quot;, 
                                &quot;Redo&quot;], [&quot;Maximize&quot;]], &quot;height&quot;: 291, &quot;width&quot;: 
                                &quot;auto&quot;, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, 
                                &quot;filebrowserUploadUrl&quot;: &quot;/ckeditor/upload/&quot;, &quot;filebrowserBrowseUrl&quot;: 
                                &quot;/ckeditor/browse/&quot;, &quot;language&quot;: &quot;en-us&quot;}" 
                data-external-plugin-resources="[]" data-id="id_course_desc" data-type="ckeditortype" required>
        {{ course.course_desc }}
        </textarea>
    </div>
    <br>
    <label for="id_course_coordinator">Course Co-Ordinator</label>
    <select name="course_coordinator" id="id_course_coordinator" required>
        {% for i in course_coordinator_list %}
        <option value="{{ i.id }}" {% if i.id == course.course_coordinator.id %} selected {% endif %}> {{ i }} </option>
        {% endfor %}
    </select>
    <br>
    <label for="id_branch">Branch</label>
    <select name="branch" id="id_branch" required>        
        {% for x,y in branch_list.fields.branch.choices %}
        <option value="{{ x }}" {% if x == course.branch %} selected {% endif %}>{{ y }}</option>
        {% endfor %}
    </select>
    <br>
    <label for="id_semester">Semester</label>
    <select name="semester" id="id_semester" required>
        {% for i in semester_list %}
        <option value="{{ i.id }}" {% if i.id == course.semester.id %} selected {% endif %}> {{ i }} </option>
        {% endfor %}
    </select>
    <br>
    <input type="submit" value="Update">
    <a href="{% url 'manage_courses' %}">Back</a>
</form>

{% endblock %}

akira_apps/staff/templates/staff/hod_templates/courses_templates/manage_courses.html
{% extends 'side_panel-navbar_dashboard.html' %}
{% load static %}

{% block content %}
{% load to_and %}
{% load first_letter_word %}

<title>{% block title %}Manage Courses - AkirA{% endblock %}</title>

<div class="main">
  {% if "Administrator" == group_list or "Head of the Department" == group_list %}
  <ul class="cards">
    <li class="cards_item">
      <div class="card create_course_card" onclick="document.location='{% url 'create_courses' %}'">
        <div class="card_image">
          <h1><i class="fa-solid fa-circle-plus"></i></h1>
        </div>
        <div class="card_content">
          <h2 class="create_card_title">Create a Course</h2>
          <p class="card_text">
            A course is a unit of teaching that typically lasts one academic term<br>
          </p>
        </div>
      </div>
    </li>
  </ul>
  {% endif %}

  <ul class="cards">
    {% for i in list_courses %}
    <li class="cards_item">
      <div class="card">
        <div class="card_image">
            <h1 class="short_title">{{ i.course_name|first_letter_word }} <sub class="custom_sub">{{ i.course_code}}</sub> </h1>
        </div>
        <div class="card_content">
          <h2 class="card_title">{{ i.course_name}}</h2>
          <p class="card_text_cc_name">Course Co-Ordinator: {{ i.course_coordinator.last_name }} {{ i.course_coordinator.first_name }}</p>                
          <p class="card_text">
            {{ i.course_desc|slice:"3:-6"|to_and|cut:"<p>"|cut:"</p>"|safe }}
          </p>
          <div class="card_buttons">
            <button class="btn more" onclick="document.location='{% url 'view_course' i.id %}'">Know More</button>
            {% if "Administrator" == group_list or "Head of the Department" == group_list %}
            <button class="btn edit" onclick="document.location='{% url 'edit_course' i.id %}'">Edit Info.</button>
            <button class="btn delete" onclick="document.location='{% url 'delete_courses' i.id %}'">Delete Course</button>
            {% else %}

            <!-- {% if "Staff" == group_list or "Course Co-Ordinator" == group_list or "Head of the Department" == group_list %}
            
              {% if i.id|stringformat:"s" in course_id_list_str %}
                <button class="btn enrolled" disabled>Course Enrolled</button>
              {% else %}
                <button class="btn enroll" onclick="document.location='{% url 'staff_enroll_course' i.id %}'">Enroll Now</button>
              {% endif %}
            
            {% else %}
            <button class="btn enroll" onclick="document.location='{% url 'staff_enroll_course' i.id %}'">Enroll Now</button>
            {% endif %} -->

            <button class="btn course_vacancy" onclick="document.location='#'">25 Left</button>
            {% endif %}
          </div>
        </div>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>

{% endblock %}