akira/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve

from django.contrib.auth.decorators import login_required
from django.urls.conf import re_path
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('akira_apps.authentication.urls')),
    path('super_admin/', include('akira_apps.super_admin.urls')),
    path('staff/', include('akira_apps.staff.urls')),
    path('student/', include('akira_apps.student.urls')),
    path('academic_registration/', include('akira_apps.academic_registration.urls')),
    path('academic/', include('akira_apps.academic.urls')),
    path('accounts/', include('akira_apps.accounts.urls')),
    path('course/', include('akira_apps.course.urls')),
    path('specialization/', include('akira_apps.specialization.urls')),
    path('shigen/', include('akira_apps.shigen.urls')),
    path('adops/', include('akira_apps.adops.urls')),
    path('', include('akira_apps.URLShortener.urls')),

    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),

    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml',TemplateView.as_view(template_name="sitemap.xml", content_type="application/xml")),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
]

akira_apps/URLShortener/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('shortURL/', views.shortURL, name="shortURL"),
    path('akira/<str:short_url>', views.shortenURL, name="shortenURL"),
]

akira_apps/URLShortener/models.py
from django.db import models
from django.contrib.auth.models import User

import uuid

class URLShortenerMC(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    ip_addr = models.GenericIPAddressField()
    bfp = models.CharField(max_length=20, null=True, blank=True)
    long_url = models.TextField()
    short_url = models.CharField(max_length=20, unique=True)
    expire_time_date = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s' % (self.user, self.short_url)
    
    class Meta:
        ordering = ["user__username", "created_at"]

class ShortenURLStat(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    shortenURL = models.ForeignKey(URLShortenerMC, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    user_ip_address = models.GenericIPAddressField()
    os_details = models.CharField(max_length=40)
    browser_details = models.CharField(max_length=40)
    visited_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s' % (self.user_ip_address, self.visited_at)

    class Meta:
        ordering = ["visited_at"]

akira_apps/URLShortener/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect

import datetime as pydt
import base64
import json
import requests
import re
import httpagentparser
import random
import string

from akira_apps.URLShortener.models import (URLShortenerMC, ShortenURLStat)

def randomString():
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(8))

def getOS_Browser_info(request):
    user_agent = request.META['HTTP_USER_AGENT']
    browser = httpagentparser.detect(user_agent)
    if not browser:
        browser = user_agent.split('/')[0]
    else:
        browser = browser['browser']['name']
    res = re.findall(r'\(.*?\)', user_agent)
    OS_Details = res[0][1:-1]
    return [browser, OS_Details]

def isLongURLSafe(request, long_url):
    in_url = long_url
    if not re.match(r'^https?://', in_url):
        in_url = 'http://' + in_url
    
    try:
        base64URL = base64.urlsafe_b64encode(in_url.encode()).decode().strip("=")
        url = "https://www.virustotal.com/api/v3/urls/%s" % (base64URL)
        headers = {
            "Accept": "application/json",
            "x-apikey": settings.VIRUS_TOTAL_API_KEY
        }

        response = requests.request("GET", url, headers=headers)
        response_json = json.loads(response.text)
        malicious_count = response_json['data']['attributes']['last_analysis_stats']['malicious']
        suspicious_count = response_json['data']['attributes']['last_analysis_stats']['suspicious']

        if malicious_count > 0 or suspicious_count > 0:
            return False
        else:
            return True
    except Exception:
        return True

def shortURL(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ipaddr = x_forwarded_for.split(',')[0]
    else:
        ipaddr = request.META.get('REMOTE_ADDR')

    getShortedURLs = URLShortenerMC.objects.filter(ip_addr=ipaddr)
    protocol = 'https' if request.is_secure() else 'http'
    domain_name = get_current_site(request).domain
    shorterner_url_prefix = protocol + '://' + domain_name + '/akira/'

    if request.method == "POST":
        if request.user.is_authenticated:
            userObj = request.user
        else:
            userObj = None

        userBFP_ID, expiretime, expiredate = None, None, None
        userBFP_ID = request.POST.get('fingerprint')

        long_url = request.POST.get('long_url').strip()
        if not re.match(r'^https?://', long_url):
            long_url = 'http://' + long_url
        customlink = request.POST.get('long_url_alias').strip()
        expire_status = request.POST.get('expire_status')
        if not expire_status == "on":
            expiredate = request.POST.get('expire_date')
            expiretime = request.POST.get('expire_time')
            expiretimedate = expiredate + " " + expiretime
        else:
            expiretimedate = None

        if customlink is None or customlink == '':
            customlink = randomString()
        if URLShortenerMC.objects.filter(short_url=customlink).exists() is False:
            if re.match("^[a-zA-Z0-9]*$", customlink):
                if isLongURLSafe(request, long_url) is True:
                    gen_short_url = str(customlink) 
                    if userObj:
                        shortenerURL = URLShortenerMC.objects.create(user=userObj,
                                                    ip_addr = ipaddr, bfp = userBFP_ID,
                                                    long_url=long_url, short_url = gen_short_url,
                                                    expire_time_date = expiretimedate)
                    else:
                        shortenerURL = URLShortenerMC.objects.create(user=userObj,
                                                    ip_addr = ipaddr, bfp = userBFP_ID,
                                                    long_url=long_url, short_url = gen_short_url,
                                                    expire_time_date = expiretimedate)
                    messages.success(request, 'URL Shortened Successfully')
                    shorterner_url = shorterner_url_prefix + shortenerURL.short_url
                    context = {
                        'shorterner_url': shorterner_url,
                    }
                    return render(request, 'URLShortener/shortURL.html', context)
                else:
                    messages.error(request, 'URL is not safe to be shortened')
            else:
                messages.error(request, "Custom link can only contain alphanumeric characters.")
        else:
            messages.error(request, "Alias is already exists.")
            messages.info(request, "Please choose simple unique alias.")
        return redirect('shortURL')
    context = {
        'getShortedURLs': getShortedURLs,
        'shorterner_url_prefix': shorterner_url_prefix,
        'protocol_current_domain': protocol + '://' + domain_name,
    }
    return render(request, 'URLShortener/shortURL.html', context)

def shortenURL(request, short_url):
    if URLShortenerMC.objects.filter(short_url=short_url).exists() is True:
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ipaddr = x_forwarded_for.split(',')[0]
        else:
            ipaddr = request.META.get('REMOTE_ADDR')
        if request.user.is_authenticated:
            userObj = request.user
        else:
            userObj = None
        shortenerURL = URLShortenerMC.objects.get(short_url=short_url)
        ShortenURLStat.objects.create(
                                shortenURL=shortenerURL,
                                user = userObj,
                                user_ip_address=ipaddr,
                                os_details = getOS_Browser_info(request)[1],
                                browser_details = getOS_Browser_info(request)[0])
        if shortenerURL.expire_time_date is not None:
            if shortenerURL.expire_time_date < pydt.datetime.now():
                messages.error(request, "This URL is expired.")
                return redirect('shortURL')
        return HttpResponseRedirect(shortenerURL.long_url)
    else:
        messages.error(request, "URL is not exists.")
        return redirect('shortURL')

akira_apps/URLShortener/templates/URLShortener/shortURL.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>URL Shortener</title>
</head>
<body>
    {% include 'messages.html' %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="long_url">Long URL</label>
        <textarea name="long_url" id="id_long_url" cols="30" rows="10" required>iakira.herokuapp.com</textarea>
        <br>
        <label for="long_url_alias">Customize your link</label>
        <input type="text" name="long_url_alias" id="id_long_url_alias">
        <br>
        <label for="expire_status">Never Expire!</label>
        <input type="checkbox" name="expire_status" id="id_expire_status" checked>
        <br>
        <input type="date" name="expire_date" id="id_expire_date">
        <input type="time" name="expire_time" id="id_expire_time">
        <br>
        <input type="hidden" name="fingerprint" id="id_fingerprint" readonly>

        <input type="hidden" name="protocol_current_domain" id="id_protocol_current_domain" data-protocol_current_domain="{{ protocol_current_domain }}">

        <input type="submit" value="Shorten">
    </form>

    <hr>
    <h3>Shortened URL</h3>
    <a href="{{ shorterner_url }}" target="_blank">{{ shorterner_url }}</a>
    {% for eachObj in getShortedURLs %}
        <a href="{{shorterner_url_prefix}}{{ eachObj.short_url }}" target="_blank">{{ eachObj.short_url }}</a>
        <br>
    {% endfor %}
    <hr>

    <script src='{% static "js/BrowserFingerPrinting.js" %}'></script>
    <script>
        var expire_status = document.getElementById('id_expire_status');
        var expire_date = document.getElementById('id_expire_date');
        var expire_time = document.getElementById('id_expire_time');
        expire_date.style.display = 'none';
        expire_time.style.display = 'none';
        expire_status.addEventListener('click', function() {
            if (expire_status.checked) {
                expire_date.style.display = 'none';
                expire_time.style.display = 'none';
            } else {
                expire_date.style.display = 'block';
                expire_time.style.display = 'block';
            }
        });

        $(document).ready(function(){
            var deviceID = uid;
            var protocolDomain = document.getElementById('id_protocol_current_domain').getAttribute('data-protocol_current_domain');
            $.ajax({
                url: protocolDomain,
                headers: {
                    'Browser-Fignerprint-ID': deviceID
                }
            });
        });
    </script>
</body>
</html>