akira/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve

from django.contrib.auth.decorators import login_required
from django.urls.conf import re_path
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('akira_apps.authentication.urls')),
    path('super_admin/', include('akira_apps.super_admin.urls')),
    path('staff/', include('akira_apps.staff.urls')),
    path('student/', include('akira_apps.student.urls')),
    path('academic_registration/', include('akira_apps.academic_registration.urls')),
    path('academic/', include('akira_apps.academic.urls')),
    path('accounts/', include('akira_apps.accounts.urls')),
    path('course/', include('akira_apps.course.urls')),
    path('specialization/', include('akira_apps.specialization.urls')),
    path('shigen/', include('akira_apps.shigen.urls')),
    path('adops/', include('akira_apps.adops.urls')),
    path('', include('akira_apps.URLShortener.urls')),

    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),

    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml',TemplateView.as_view(template_name="sitemap.xml", content_type="application/xml")),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
]

akira_apps/student/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('student_dashboard/', views.student_dashboard, name = 'student_dashboard'),
    path('add_student/', views.add_student, name = 'add_student'),
    path('manage_students/', views.manage_students, name = 'manage_students'),
    path('view_student/<student_username>/', views.view_student, name = 'view_student'),
    path('bulk_upload_students_save/', views.bulk_upload_students_save, name = 'bulk_upload_students_save'),
    path('students_info_csv/', views.students_info_csv, name = 'students_info_csv'),
    path('search_student/', views.search_student, name='search_student'),
]

akira_apps/student/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator


import uuid
import datetime as pydt

from akira_apps.academic.models import (Branch)
from akira_apps.staff.models import (Skills)

GENDER_CHOICES = [
    ("", "Select Gender"),
    ("Male", "Male"),
    ("Female", "Female"),
]

BLOOD_GROUP_CHOICES = [
    ("","Blood Group"),
    ("A+","A+"),
    ("A-","A-"),
    ("B+","B+"),
    ("B-","B-"),
    ("O+","O+"),
    ("O-","O-"),
    ("AB+","AB+"),
    ("AB-","AB-"),
]

MOTHER_TOUNGE_CHOICES = [
    ("","Mother Tounge"),
    ("Hindi","Hindi"),
    ("English","English"),
    ("Bengali","Bengali"),
    ("Marathi","Marathi"),
    ("Telugu","Telugu"),
    ("Tamil","Tamil"),
    ("Gujarati","Gujarati"),
    ("Urdu","Urdu"),
    ("Kannada","Kannada"),
    ("Odia","Odia"),
    ("Malayalam","Malayalam"),
    ("Punjabi","Punjabi"),
]

def atLeastAgeofMajority(value):
    inputDate = str(value)
    inputDate = pydt.datetime.strptime(inputDate, '%Y-%m-%d')
    today = pydt.datetime.today()
    diff = today - inputDate
    if not ((diff.days//365) >= 18):
        raise ValidationError("You are not 18 years old.")
    inputDate = str(value)
    inputDate = pydt.datetime.strptime(inputDate, '%Y-%m-%d')
    current_year = pydt.datetime.today().year
    max_year = int(current_year) - 18
    # min_year = int(max_year) - 3
    year = inputDate.year
    if year <= max_year:
        today = pydt.datetime.today()
        diff = today - inputDate
        if not ((diff.days//365) >= 18):
            raise ValidationError("You are not 18 years old.")
    else:
        raise ValidationError("Invalid DOB")

class Students(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    user = models.OneToOneField(User, unique=True, on_delete = models.CASCADE)
    gender = models.CharField(max_length=14, choices = GENDER_CHOICES, default=1)
    date_of_birth = models.DateField(validators = [atLeastAgeofMajority])
    blood_group = models.CharField(max_length=18, choices = BLOOD_GROUP_CHOICES, default=1)
    phone = models.CharField(max_length = 15)
    door_no = models.CharField(max_length=10)
    zip_code = models.IntegerField()
    city = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    photo = models.ImageField(null=True, blank=True, upload_to='student_photos/', validators=[FileExtensionValidator(['jpg', 'png', 'jpeg'])])
    branch = models.ForeignKey(Branch, on_delete = models.DO_NOTHING, blank = True, null = True)
    about = models.TextField(max_length=500, null=True, blank=True)
    skills = models.ManyToManyField(Skills, blank = True)
    resume = models.FileField(upload_to ='student_resumes/', validators=[FileExtensionValidator(['pdf'])], blank = True, null = True)

    def __str__(self):
        return '%s %s %s' % (self.user, self.user.first_name.title(), self.user.last_name.title())

# class course_registration_student(models.Model):
#     id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
#     student = models.ForeignKey(User, on_delete = models.SET_NULL, blank = True, null = True)
#     course = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
#     section = models.ForeignKey(SectionRooms, on_delete=models.SET_NULL, blank=True, null=True)

#     class Meta:
#         unique_together = ('course','section')

akira_apps/student/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.contrib.auth.models import Group, User
from django.http.response import HttpResponse
from django.conf import settings
from django.db.models import Q
from django.contrib import messages

import secrets
import pandas as pd
import io
import csv
import datetime as pydt
import random
import string

from akira_apps.academic.models import (Branch)
from akira_apps.student.models import (Students)
from akira_apps.super_admin.forms import (BLOODGROUPForm, GENDERCHOICESForm)

@login_required(login_url=settings.LOGIN_URL)
def student_dashboard(request):
    rAnd0m123 = secrets.token_urlsafe(16)
    context = {
        "rAnd0m123":rAnd0m123,
    }
    return render(request, 'student/dashboard.html', context)

@login_required(login_url=settings.LOGIN_URL)
def manage_students(request):
    students = Students.objects.all()
    context = {
        "students":students,
    }
    return render(request, 'student/manage_students/manage_students.html', context)

@login_required(login_url=settings.LOGIN_URL)
def view_student(request, student_username):
    student = Students.objects.get(user__username=student_username)
    user = User.objects.get(username=student_username)
    list_groups = Group.objects.all()
    current_user_group = ', '.join(map(str, user.groups.all()))
    context = {
        "student": student,
        "current_user_group":current_user_group,
        "list_groups":list_groups,
    }
    return render(request, 'student/manage_students/view_student.html', context)

@login_required(login_url=settings.LOGIN_URL)
def students_info_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=students_info_record' + \
        str(pydt.pydt.datetime.now()) + '.csv'

    writer = csv.writer(response)
    writer.writerow(['Username', 'First Name', 'Last Name', 'Email', 
                    'Gender', 'Date of Birth',
                    'Blood Group', 'Door No.', 'Zip Code', 'City Name', 
                    'State Name', 'Country', 'Branch', 'Current Medical Issue', 'Designation'])
    
    students = Students.objects.all()

    for i in students:
        writer.writerow([i.user.username, i.user.first_name, i.user.last_name, i.user.email,
                        i.gender, i.date_of_birth,
                        i.blood_group, i.door_no, i.zip_code, i.city_name, 
                        i.state_name, i.country_name, i.branch, i.current_medical_issue, ', '.join(map(str, i.user.groups.all()))])
    return response

@login_required(login_url=settings.LOGIN_URL)
def bulk_upload_students_save(request):
    if request.method == 'POST':
        student_from_db = User.objects.all()
        student_user=[]
        for i in student_from_db:
            student_user.append(i.username)
            student_user.append(i.email)

        paramFile = io.TextIOWrapper(request.FILES['student_file'].file)
        data = pd.read_csv(paramFile)
        data.drop_duplicates(subset ="Username", keep = 'first', inplace = True)

        for index, row in data.iterrows():
            if str(row['Username']) not in student_user and str(row['Email']) not in student_user:
                newuser = User.objects.create_user(
                    username=row['Username'],
                    first_name=row['First Name'],
                    last_name=row['Last Name'],
                    email=row['Email'],
                    password="AKIRAaccount@21",
                )
                group_name = row['Designation']
                my_group = Group.objects.get(name='%s' % str(group_name))
                my_group.user_set.add(newuser)

                student = Students.objects.bulk_create([
                    Students(
                        user_id = newuser.id,
                        gender=row['Gender'],
                        date_of_birth=(row['Date of Birth'] if row['Date of Birth'] != '' else '1998-12-01'),
                        door_no=row['Door No.'],
                        zip_code=row['Zip Code'],
                        city_name=row['City Name'],
                        state_name=row['State Name'],
                        country_name=row['Country'],
                        current_medical_issue=row['Current Medical Issue'],
                        blood_group=row['Blood Group'],
                        branch=row['Branch'],
                    )
                ])
        return redirect('manage_students')
    else:
        return redirect('manage_students')

@login_required(login_url=settings.LOGIN_URL)
def search_student(request):
    if request.method == 'POST':
        query = request.POST['search-student'].strip()
        beforeSearch = pydt.datetime.now()
        students = Students.objects.filter(
            Q(user__username__icontains=query) | Q(user__email__icontains=query) | Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query) | Q(gender__icontains=query) |
            Q(date_of_birth__icontains=query) | Q(zip_code__icontains=query) |
            Q(city_name__icontains=query) | Q(state_name__icontains=query) |
            Q(country_name__icontains=query) | Q(current_medical_issue__icontains=query) |
            Q(blood_group__icontains=query) | Q(branch__icontains=query)
        )
        afterSearch = pydt.datetime.now()
        totalTimeTaken = (afterSearch - beforeSearch).total_seconds()
        context = {
            'students': students,
            'totalTimeTaken':totalTimeTaken,
            'query':query,
        }
        return render(request, 'student/manage_students/search_student.html', context)
    else:
        messages.info(request, "We could process your request!")
        return redirect('manage_students')

def add_student(request):
    gender = GENDERCHOICESForm()
    blood_groups = BLOODGROUPForm()
    branches = Branch.objects.all()
    last_student = User.objects.filter(groups__name='Student').last()

    if request.method == "POST":
        username = request.POST.get('username')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        email = request.POST.get('email')
        password = ''.join(random.choice(string.ascii_letters + string.digits + string.punctuation) for i in range(random.randint(14, 18)))
        gender = request.POST.get('gender')
        date_of_birth = request.POST.get('date_of_birth')
        door_no = request.POST.get('door_no')
        zip_code = request.POST.get('zip_code')
        city = request.POST.get('city')
        state = request.POST.get('state')
        country = request.POST.get('country')
        blood_group = request.POST.get('blood_group')
        branch = request.POST.get('branch')
        branch = Branch.objects.get(id=branch)
        if 'photo' in request.FILES:
            photo = request.FILES['photo']
        else:
            photo = False
        save = request.POST.get('_save')
        addanother = request.POST.get('_addanother')

        if User.objects.filter(username = username).exists() is False:
            try:
                user = User.objects.create_user(
                    username = username,
                    email = email,
                    first_name = firstname,
                    last_name = lastname
                )
                user.set_password(password)
                user.save()

                student = Students.objects.create(
                    user = user,
                    gender = gender,
                    date_of_birth = date_of_birth,
                    door_no = door_no,
                    zip_code = zip_code,
                    city = city,
                    state = state,
                    country = country,
                    blood_group = blood_group,
                    photo = photo,
                    branch = branch
                )
            except Exception as e1:
                try:
                    user.delete()
                    student.delete()
                except Exception as e2:
                    messages.error(request, str(e2))
                messages.error(request, str(e1))
                return redirect('add_student')
            if save:
                messages.success(request, "Student added successfully!")
                return redirect('manage_students')
            elif addanother:
                messages.success(request, "Student added successfully!")
                return redirect('add_student')
            else:
                messages.success(request, "Student added successfully!")
                return redirect('edit_student', stdID = user.id)
        else:
            messages.info(request, "%s already exists!" % username)
            return redirect('add_student')
    context = {
        'gender': gender,
        'blood_groups': blood_groups,
        'branches': branches,
    }
    return render(request, "student/manage_students/add_student.html", context)

akira_apps/student/templates/student/manage_students/add_student.html
{% extends 'side_panel-navbar_dashboard.html' %}
{% load static %}

{% block add-students %}

    <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="username" id="id_username" placeholder="Username" required>
        <input type="email" name="email" id="id_email" placeholder="Email" required>
        <input type="text" name="firstname" id="id_firstname" placeholder="First name" required>
        <input type="text" name="lastname" id="id_lastname" placeholder="Last name" required>

        <select name="gender" id="id_gender">
            {% for x,y in gender.fields.gender.choices %}
            <option value="{{ x }}">{{ y }}</option>
            {% endfor %}
        </select>
        <input type="date" name="date_of_birth" id="id_date_of_birth" placeholder="Date of birth" required>
        <input type="text" name="door_no" id="id_door_no" placeholder="Door No." required>
        <input type="number" name="zip_code" id="id_zip_code" placeholder="Zip code." required>
        <input type="text" name="city" id="id_city" placeholder="City" required>
        <input type="text" name="state" id="id_state" placeholder="State" required>
        <input type="text" name="country" id="id_country" placeholder="Country" required>
        <select name="blood_group" id="id_blood_group">
            {% for x,y in blood_groups.fields.bloodgroup.choices %}
            <option value="{{ x }}">{{ y }}</option>
            {% endfor %}
        </select>
        <input type="file" name="photo" accept="image/*" id="id_photo">
        <select name="branch" id="id_branch">
            <option value="">Select Branch</option>
            {% for i in branches %}
            <option value="{{ i.id }}">{{ i.name }}</option>
            {% endfor %}
        </select>
        <a href="{% url 'add_branch' %}" target="_blank" rel="noopener noreferrer">Create branch</a>
        <div class="fetchBranches" id="fetchBranches">refresh</div>
        
        <input type="submit" value="Save" class="default" name="_save">
        <input type="submit" value="Save and add another" name="_addanother">
        <input type="submit" value="Save and continue editing" name="_continue">
    </form>

    <script>
        $("[id = 'fetchBranches']").click(function () {
            $.ajax({
                type: "GET",
                url: '{% url "getAllBranches" %}',
                success: function (data) {
                    let html_data = '<option value=""> Select Branch </option>';
                    data.forEach(function (data) {
                        html_data += `<option value="${data.id}">${data.name}</option>`
                    });
                    $("#id_branch").html(html_data);
                }
            });
        });
      </script>

{% endblock %}

akira_apps/student/templates/student/manage_students/manage_students.html
{% extends 'side_panel-navbar_dashboard.html' %}
{% load static %}
{% load user_group %}

{% block content %}

{% block analytics-text %}
<h1>Manage Students</h1>
<p>Display analytics about your Students <span class="fas fa-chart-line"></span> </p>
{% endblock %}

{% block analytic-overview %}
<section>
  <h3 class="section-head">Overview</h3>
</section>
<div class="analytics">
  <div class="analytic">
      <div class="analytic-icon">
          <span class="fa-solid fa-users"></span>
      </div>
      <div class="analytic-info">
          <h4>Total Students</h4>
          <h1>{{ students|length }}</h1>
      </div>
  </div>
  <div class="analytic">
    <div class="analytic-icon">
        <span class="fa-solid fa-user"></span>
    </div>
    <div class="analytic-info">
        <h4>Y20 Students</h4>
        <h1>{{ students|length }}</h1>
    </div>
  </div>
  <div class="analytic">
      <div class="analytic-icon">
          <span class="fa-solid fa-user"></span>
      </div>
      <div class="analytic-info">
          <h4>Y19 Students</h4>
          <h1>{{ students|length }}</h1>
      </div>
  </div>
  <div class="analytic">
    <div class="analytic-icon">
        <span class="fas fa-user-graduate"></span>
    </div>
    <div class="analytic-info">
        <h4>Y18 Students</h4>
        <h1>{{ students|length }}</h1>
    </div>
  </div>
</div>
{% endblock %}

{% block manage-students %}
<button onClick='window.location="{% url "add_student" %}"' class="add-faculty">Add Student</button>
<button id="showFormBulkImport" class="add-faculty">Bulk Import</button>


<div id="myModal" class="modal">
  <div class="model-container">
    <div class="modal-content">
      <span id="close-model" class="close">&times;</span>
      <form action="{% url 'bulk_upload_students_save' %}" method="POST" enctype="multipart/form-data">
        <div class="drop-zone">
          <span class="drop-zone__prompt">
            <i class="fa-solid fa-file fileUploadIcon"></i> <br>
            Drop file here or click to upload</span>
          {% csrf_token %}
            <input type="file" name="student_file" class="drop-zone__input" accept=".csv" required>
        </div>
        <input type="submit" class="bulkUploadButton" value="Bulk Upload">
      </form>
    </div>
  </div>
</div>

<script src="{% static 'js/fileDragUpload.js' %}"></script>

{% if students %}
<div class="search-box-container">
  <form method="post" action="{% url 'search_student' %}" class="form-elements">
    {% csrf_token %}
    <input type="text" name="search-student" id="search-bar" placeholder="Search Students..." autocomplete="off" required>
    <button type="submit" class="search-icon"><i class="fa-solid fa-magnifying-glass"></i></button>
  </form>
</div>

<div class="list-all-faculty">
  {% for student in students %}
  <div class="staff-profile-card"
  style="--card-top-color: #14c66fab;"
  >
    <div class="staff-profile-img">
      <img
        {% if not student.profile_pic %}
        src="{% get_static_prefix %}Default User Profile Photo/{{student.user.first_name|capfirst|first}}.png" 
        {% else %}
        src="{{ student.profile_pic.url }}"
        {% endif %}
        alt="Student Profile Pic">
    </div>
    <div class="staff-profile-infos">
      <div class="staff-profile-name">
        <h2>{{ student.name_prefix }} {{ student.user.first_name|title }} {{ student.user.last_name|title }}</h2>
        <h4>@{{ student.user.username }}</h4>
      </div>
      <p class="staff-profile-text">
        I'm a {{ student.user|user_group }} in {{ student.branch }} department.
      </p>
      <ul class="staff-profile-stats">
        <li>
          <h3>2</h3>
          <h4>Research</h4>
        </li>
        <li>
          <h3>4</h3>
          <h4>Projects</h4>
        </li>
      </ul>
      <div class="staff-profile-links">
        <button class="staff-profile-follow">Contact</button>
        <button class="staff-profile-view" onclick="document.location='{% url 'view_student' student.user.username %}'">View profile</button>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<h1 style="text-align: center; margin-top: 5rem; color: var(--large-text-color);">Data Not Available</h1>
{% endif %}
<script>
var modal = document.getElementById("myModal");
var btn = document.getElementById("showFormBulkImport");
var span = document.getElementById("close-model");

btn.onclick = function() {
  modal.style.display = "block";
}

span.onclick = function() {
  modal.style.display = "none";
}

window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>
{% endblock %}

{% endblock %}

akira_apps/student/templates/student/manage_students/search_student.html
{% extends 'side_panel-navbar_dashboard.html' %}
{% load static %}
{% load humanize %}
{% load user_group %}

{% block content %}

{% block analytics-text %}
<h1>Search Students...</h1>
{% endblock %}

{% block manage-students %}

<div class="search-box-container">
  <form method="post" action="{% url 'search_student' %}" class="form-elements">
    {% csrf_token %}
    <input type="text" name="search-student" id="search-bar" placeholder="Search Students..." value="{{ query }}" autocomplete="off" required>
    <button type="submit" class="search-icon"><i class="fa-solid fa-magnifying-glass"></i></button>
  </form>
</div>

{% if students %}
<p class="search-result-text">About {{ students|length|intcomma }} result{{ students|length|pluralize }} ({{totalTimeTaken}} seconds)</p>
{% endif %}

<div class="list-all-faculty">
  {% for student in students %}
  <div class="staff-profile-card"
  style="--card-top-color: #14c66fab;"
  >
    <div class="staff-profile-img">
      <img
        {% if not student.profile_pic %}
        src="{% get_static_prefix %}Default User Profile Photo/{{student.user.first_name|capfirst|first}}.png" 
        {% else %}
        src="{{ student.profile_pic.url }}"
        {% endif %}
        alt="Student Profile Pic">
    </div>
    <div class="staff-profile-infos">
      <div class="staff-profile-name">
        <h2>{{ student.name_prefix }} {{ student.user.first_name|title }} {{ student.user.last_name|title }}</h2>
        <h4>@{{ student.user.username }}</h4>
      </div>
      <p class="staff-profile-text">
        I'm a {{ student.user|user_group }} in {{ student.branch }} department.
      </p>
      <ul class="staff-profile-stats">
        <li>
          <h3>2</h3>
          <h4>Research</h4>
        </li>
        <li>
          <h3>4</h3>
          <h4>Projects</h4>
        </li>
      </ul>
      <div class="staff-profile-links">
        <button class="staff-profile-follow">Contact</button>
        <button class="staff-profile-view" onclick="document.location='{% url 'view_student' student.user.username %}'">View profile</button>
      </div>
    </div>
  </div>
  {% empty %}
    <div class="query-search-result">
      <p class="search-result-text">Your search - <b>{{ query }}</b> - did not match any documents.</p>
      <p class="search-result-text">Suggestions:</p>
      <ul class="search-result-text">
          <li class="search-result-text">&nbsp;Make sure that all words are spelled correctly.</li>
          <li class="search-result-text">&nbsp;Try different keywords.</li>
          <li class="search-result-text">&nbsp;Try more general keywords.</li>
      </ul>
    </div>
  {% endfor %}
</div>
{% endblock %}

{% endblock %}

akira_apps/student/templates/student/manage_students/view_student.html
{% extends 'side_panel-navbar_dashboard.html' %}
{% load static %}
{% block content %}
{% load humanize %}

{% block view-student %}

<img
{% if not student.profile_pic %}
src="{% get_static_prefix %}Default User Profile Photo/{{student.user.first_name|capfirst|first}}.png" 
{% else %}
src="{{ student.profile_pic.url }}"
{% endif %}
alt="staff Profile Pic">

First Name: {{ student.user.first_name }}
<br>
Last Name: {{ student.user.last_name }}
<br>
Gender: {{ student.gender }}
<br>
Date of Birth: {{ student.date_of_birth }}
<br>
Door No. {{ student.door_no }}
<br>
Zip Code: {{ student.zip_code }}
<br>
City: {{ student.city_name }}
<br>
State: {{ student.state_name }}
<br>
Country: {{ student.country_name }}
<br>
Current Medical Issue: {{ student.current_medical_issue }}
<br>
Blood Group: {{ student.blood_group }}
<br>
Designation: {{ current_user_group }}
<br>
User Login Details:
<br>
{{ student.user.last_login|naturaltime }} | {{ student.user.last_login }}

<form action="{% url 'assign_user_group' student.user.username %}" method="POST">
    {% csrf_token %}
    <select name="designation-group" id="id_designation-group" required>
        <option value="">Choose Designation</option>
        {% for i in list_groups %}
        <option value="{{ i }}">{{ i }}</option>
        {% endfor %}
    </select>
    <input type="submit">
</form>

<a href="#">Edit Student</a>

{% endblock %}

{% endblock %}
{% url 'edit_staff' student.user.username %}