akira/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve

from django.contrib.auth.decorators import login_required
from django.urls.conf import re_path
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views
from django.views.generic.base import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('akira_apps.authentication.urls')),
    path('super_admin/', include('akira_apps.super_admin.urls')),
    path('staff/', include('akira_apps.staff.urls')),
    path('student/', include('akira_apps.student.urls')),
    path('academic_registration/', include('akira_apps.academic_registration.urls')),
    path('academic/', include('akira_apps.academic.urls')),
    path('accounts/', include('akira_apps.accounts.urls')),
    path('course/', include('akira_apps.course.urls')),
    path('specialization/', include('akira_apps.specialization.urls')),
    path('shigen/', include('akira_apps.shigen.urls')),
    path('adops/', include('akira_apps.adops.urls')),
    path('', include('akira_apps.URLShortener.urls')),

    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),

    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml',TemplateView.as_view(template_name="sitemap.xml", content_type="application/xml")),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
]

akira_apps/adops/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('manage_adops/', views.manage_adops, name='manage_adops'),
    path('add_openings/', views.add_openings, name='add_openings'),
    path('editOpening/<str:openingID>/', views.editOpening, name='editOpening'),
    path('deleteOpening/<str:openingID>/', views.deleteOpening, name='deleteOpening'),
    path('userAppliedOpenings/', views.userAppliedOpenings, name='userAppliedOpenings'),
    path('withdrawAppl/<str:openingID>/', views.withdrawAppl, name='withdrawAppl'),
    path('applicantsInfo/<str:openingID>/', views.applicantsInfo, name='applicantsInfo'),

    path('profile/', views.profile, name='profile'),

    path('openings/', views.openings, name='openings'),

    path('applicantsAccount/', views.applicantsAccount, name='applicantsAccount'),
    path('confirm_applicant_email/<uidb64>/<token>/', views.confirm_applicant_email, name='confirm_applicant_email'),
    path('send_applicant_reg_email_again/<username>/', views.send_applicant_reg_email_again, name = 'send_applicant_reg_email_again'),

    path('fetch_each_opening_Ajax/', views.fetch_each_opening_Ajax, name='fetch_each_opening_Ajax'),
    path('fetch_each_applicant_Ajax/', views.fetch_each_applicant_Ajax, name='fetch_each_applicant_Ajax'),
    # path('draft_opening_Ajax/', views.draft_opening_Ajax, name='draft_opening_Ajax'),
]

akira_apps/adops/models.py
from django.contrib.auth.models import User
from django.db import models

import uuid

JOB_TYPE_CHOICES = [
    ("", "Select Job Type"),
    ("Full Time", "Full Time"),
    ("Part Time", "Part Time"),
    ("Contract", "Contract"),
    ("Internship", "Internship"),
    ("Temporary", "Temporary"),
    ("Freelance", "Freelance"),
    ("Volunteer", "Volunteer"),
    ("Work From Home", "Work From Home"),
]

class Openings(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    job = models.CharField(max_length=100)
    overview = models.TextField(max_length=400)
    description = models.TextField(max_length=2000)
    experience = models.CharField(max_length=20)
    qualification = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    pay_scale = models.CharField(max_length=50)
    type = models.CharField(max_length=15, blank=True, null=True, choices = JOB_TYPE_CHOICES, default=1)
    contact_person = models.ForeignKey(User, on_delete=models.CASCADE)
    applied = models.ManyToManyField(User, related_name='applied_to', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s' % (self.job)

    class Meta: 
        ordering = ['created_at']
        unique_together = ['job', 'location']

FIELD_VALUE_TYPE = [
    ("", "Select Field Value Type"),
    ("text", "text"),
    ("number", "number"),
    ("textarea", "textarea"),
]

class ExtraFieldOpenings(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    name = models.TextField(max_length=500)
    value = models.TextField(max_length=500)
    value_type = models.CharField(max_length=10,  choices = FIELD_VALUE_TYPE, default=1)
    mappingto = models.ForeignKey(Openings, on_delete=models.CASCADE)

    def __str__(self):
        return '%s' % (self.name)

akira_apps/staff/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

import uuid

from akira_apps.academic.models import (Branch)

GENDER_CHOICES = [
    ("", "Select Gender"),
    ("Male", "Male"),
    ("Female", "Female"),
]

BLOOD_GROUP_CHOICES = [
    ("","Blood Group"),
    ("A+","A+"),
    ("A-","A-"),
    ("B+","B+"),
    ("B-","B-"),
    ("O+","O+"),
    ("O-","O-"),
    ("AB+","AB+"),
    ("AB-","AB-"),
]

MOTHER_TOUNGE_CHOICES = [
    ("","Mother Tounge"),
    ("Hindi","Hindi"),
    ("English","English"),
    ("Bengali","Bengali"),
    ("Marathi","Marathi"),
    ("Telugu","Telugu"),
    ("Tamil","Tamil"),
    ("Gujarati","Gujarati"),
    ("Urdu","Urdu"),
    ("Kannada","Kannada"),
    ("Odia","Odia"),
    ("Malayalam","Malayalam"),
    ("Punjabi","Punjabi"),
]

Name_Prefix_Choices = [
    ("","Select Name Prefix"),
    ("Dean","University Dean"),
    ("Dr","Doctor (Medical or Educator)"),
    ("Hon","Honorable"),
    ("Mr","Mister"),
    ("Mrs","Married Woman"),
    ("Ms","Single/Unmarried Women"),
    ("Prof","Professor"),
]

class Staff(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    user = models.OneToOneField(User, unique=True, on_delete = models.CASCADE)
    name_prefix = models.CharField(max_length = 35, choices = Name_Prefix_Choices, default=1)
    gender = models.CharField(max_length=14, choices = GENDER_CHOICES, default=1)
    date_of_birth = models.DateField()
    blood_group = models.CharField(max_length=18, choices = BLOOD_GROUP_CHOICES, default=1)
    phone = models.CharField(max_length = 15)
    door_no = models.CharField(max_length=10)
    zip_code = models.IntegerField()
    city = models.CharField(max_length=50)
    district = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    photo = models.ImageField(null=True, blank=True, upload_to='staff_photos/', validators=[FileExtensionValidator(['jpg', 'png', 'jpeg'])])
    branch = models.ForeignKey(Branch, on_delete = models.DO_NOTHING, blank = True, null = True)
    about = models.TextField(max_length=500, null=True, blank=True)
    skills = models.ManyToManyField('Skills', blank = True)
    resume = models.FileField(upload_to ='staff_resumes/', validators=[FileExtensionValidator(['pdf'])], blank = True, null = True)

    def __str__(self):
        return '%s %s %s' % (self.user, self.user.first_name.title(), self.user.last_name.title())
    
    class Meta:
        ordering = ["user__first_name"]

class Skills(models.Model):
    id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
    name = models.CharField(max_length = 50, unique=True)

    def __str__(self):
        return self.name

# class UserExtraFields(models.Model):
#     id = models.UUIDField(primary_key = True, unique = True, default = uuid.uuid4, editable = False)
#     staffMC = models.ForeignKey(Staff, on_delete = models.CASCADE)
#     field_name = models.CharField(max_length = 100)
#     field_value = models.TextField(max_length=500)

#     def __str__(self):
#         return '%s' % (self.field_name)

akira_apps/adops/forms.py
from django import forms
from .models import (JOB_TYPE_CHOICES, FIELD_VALUE_TYPE)

class OpeningsJobTypeForm(forms.Form):
    job_type = forms.ChoiceField(choices = JOB_TYPE_CHOICES)

class ExtraFieldValueTypeForm(forms.Form):
    field_value_type = forms.ChoiceField(choices = FIELD_VALUE_TYPE)

akira_apps/adops/templates/adops/openings/add_opening.html
{% extends 'side_panel-navbar_dashboard.html' %}
{% load static %}

{% block analytics-text %}

{% if editOpeningID %}
<h1>Edit Opening</h1>
<p>{{ openingIDObj.job }}</p>
{% else %}
<h1>Create Opening</h1>
<p>Create the Opening <span class="fas fa-chart-line"></span> </p>
{% endif %}

{% endblock %}

{% block create-openings %}
<div class="main-container-fluid">
  <div class="container-fluid">
  <div class="regiserformcontainer">
      <form id="msform" class="block_form" autocomplete="off" action="" method="POST">
        {% csrf_token %}
        <fieldset>
          <div class="form-card">
            <div class="field-container">
              <div class="input-box">
                <label class="fieldlabels input-label" for="id_job_name">Job name</label> 
                <input type="text" name="job" id="id_job_name" class="input-1" onfocus="setFocus(true)" onblur="setFocus(false)" required>
                <span class="error-text">Enter job title</span>
              </div>
            </div>

            <div class="field-container">
              <div class="input-box">
                <label class="fieldlabels input-label" for="id_job_overview">Overview</label>
                <textarea name="overview" maxlength="400" id="id_job_overview" class="input-1" onfocus="setFocus(true)" onblur="setFocus(false)" required></textarea>
                <span class="help-text">Seperate sentence by '#'.</span>
                <span class="help-text">Maximum characters allowed is 400 only.</span>
                <span class="error-text">Enter job overview</span>
                <span class="info-text"></span>
              </div>
            </div>

            <div class="field-container">
              <div class="input-box">
                <label class="fieldlabels input-label" for="id_job_description">Description</label>
                <textarea name="description" maxlength="2000" id="id_job_description" class="input-1" onfocus="setFocus(true)" onblur="setFocus(false)" required></textarea>
                <span class="help-text">Seperate sentence by '#'.</span>
                <span class="help-text">Maximum characters allowed is 2000 only.</span>
                <span class="error-text">Enter job description</span>
                <span class="info-text"></span>
              </div>
            </div>

            <div class="field-container">
              <div class="input-box">
                  <label class="fieldlabels input-label" for="id_experience">Experience</label> 
                  <input type="text" name="experience" id="id_experience" class="input-1" onfocus="setFocus(true)" onblur="setFocus(false)" required>
                  <span class="error-text">Enter experience</span>
              </div>
              <div class="input-box">
                  <label class="fieldlabels input-label" for="id_qualification">Qualification</label> 
                  <input type="text" name="qualification" id="id_qualification" class="input-1" onfocus="setFocus(true)" onblur="setFocus(false)" required>
                  <span class="error-text">Enter qualification</span>
              </div>
            </div>

            <div class="field-container">
                <div class="input-box">
                    <label class="fieldlabels input-label" for="id_location">Location</label> 
                    <input type="text" name="location" id="id_location" class="input-1" onfocus="setFocus(true)" onblur="setFocus(false)" required>
                    <span class="error-text">Enter location</span>
                </div>
              <div class="input-box">
                  <label class="fieldlabels input-label" for="id_pay_scale">Pay scale</label> 
                  <input type="text" name="pay_scale" id="id_pay_scale" class="input-1" onfocus="setFocus(true)" onblur="setFocus(false)" required>
                  <span class="error-text">Enter pay scale</span>
              </div>
            </div>

            <div class="field-container mb-1rem">
              <div class="input-box active-grey">
                  <label class="fieldlabels input-label" for="id_job_type">Job type</label>
                  <select name="job_type" class="input-1" id="id_job_type" required>
                      {% for x,y in job_type_list.fields.job_type.choices %}
                      <option value="{{ x }}" {% if x == openingIDObj.type %} selected {% endif %}>{{ y }}</option>
                      {% empty %}
                      <option value="">Data Not Available</option>
                      {% endfor %}
                  </select>
                  <span class="error-text">Select Job type</span>
              </div>
              <div class="input-box active-grey">
                  <label class="fieldlabels input-label" for="id_contact_person">Contact person</label>
                  <select name="contact_person" class="input-1" id="id_contact_person" required>
                      <option value="">Select Contact Person</option>
                      {% for i in contact_person %}
                      <option value="{{i.id}}" {% if i.id == openingIDObj.contact_person.id %} selected {% endif %}>{{i.first_name}} {{i.last_name}}</option>
                      {% empty %}
                      <option value="">Data Not Available</option>
                      {% endfor %}
                  </select>
                  <span class="error-text">Select contact person</span>
              </div>
            </div>
          </div>
          <button id="create_opening-btn" class="action-button create_opening-btn">Create</button>
          <button type="button" id="cancel-btn" data-redirect-url="{% url 'manage_adops' %}" class="action-button-cancel">Cancel</button>
        </fieldset>
      </form>
  </div>
</div>
</div>

<script src="{% static 'js/add-opening.js' %}"></script>
{% endblock %}

akira_apps/adops/templates/adops/openings/edit_opening.html
{% extends 'side_panel-navbar_dashboard.html' %}
{% load static %}

{% block analytics-text %}
<h1>Edit Opening</h1>
<p>{{ openingIDObj.job }}</p>
{% endblock %}

{% block edit-openings %}
<div class="regiserformcontainer">
    <form id="msform" class="block_form" autocomplete="off" action="" method="POST">
      {% csrf_token %}
      <fieldset>
        <div class="form-card">
          <div class="field-container">
            <div class="input-box">
              <label class="fieldlabels input-label" for="id_job_name">Job name</label> 
              <input type="text" name="job" id="id_job_name" class="input-1" value="{{ openingIDObj.job }}" onfocus="setFocus(true)" onblur="setFocus(false)" required>
              <span class="error-text">Enter job title</span>
            </div>
          </div>

          <div class="field-container">
            <div class="input-box">
              <label class="fieldlabels input-label" for="id_job_overview">Overview</label>
              <textarea name="overview" maxlength="400" id="id_job_overview" class="input-1" onfocus="setFocus(true)" onblur="setFocus(false)" required>{{ openingIDObj.overview }}</textarea>
              <span class="help-text">Seperate sentence by '#'.</span>
              <span class="help-text">Maximum characters allowed is 400 only.</span>
              <span class="error-text">Enter job overview</span>
              <span class="info-text"></span>
            </div>
          </div>

          <div class="field-container">
            <div class="input-box">
              <label class="fieldlabels input-label" for="id_job_description">Description</label>
              <textarea name="description" maxlength="2000" id="id_job_description" class="input-1" onfocus="setFocus(true)" onblur="setFocus(false)" required>{{ openingIDObj.description }}</textarea>
              <span class="help-text">Seperate sentence by '#'.</span>
              <span class="help-text">Maximum characters allowed is 2000 only.</span>
              <span class="error-text">Enter job description</span>
              <span class="info-text"></span>
            </div>
          </div>

          <div class="field-container">
            <div class="input-box">
                <label class="fieldlabels input-label" for="id_experience">Experience</label> 
                <input type="text" name="experience" id="id_experience" class="input-1" value="{{ openingIDObj.experience }}" onfocus="setFocus(true)" onblur="setFocus(false)" required>
                <span class="error-text">Enter experience</span>
            </div>
            <div class="input-box">
                <label class="fieldlabels input-label" for="id_qualification">Qualification</label> 
                <input type="text" name="qualification" id="id_qualification" class="input-1" value="{{ openingIDObj.qualification }}" onfocus="setFocus(true)" onblur="setFocus(false)" required>
                <span class="error-text">Enter qualification</span>
            </div>
          </div>

          <div class="field-container">
              <div class="input-box">
                  <label class="fieldlabels input-label" for="id_location">Location</label> 
                  <input type="text" name="location" id="id_location" class="input-1" value="{{ openingIDObj.location }}" onfocus="setFocus(true)" onblur="setFocus(false)" required>
                  <span class="error-text">Enter location</span>
              </div>
            <div class="input-box">
                <label class="fieldlabels input-label" for="id_pay_scale">Pay scale</label> 
                <input type="text" name="pay_scale" id="id_pay_scale" class="input-1" value="{{ openingIDObj.pay_scale }}" onfocus="setFocus(true)" onblur="setFocus(false)" required>
                <span class="error-text">Enter pay scale</span>
            </div>
          </div>

          <div class="field-container mb-1rem">
            <div class="input-box active-grey">
                <label class="fieldlabels input-label" for="id_job_type">Job type</label>
                <select name="job_type" class="input-1" id="id_job_type" required>
                    {% for x,y in job_type_list.fields.job_type.choices %}
                    <option value="{{ x }}" {% if x == openingIDObj.type %} selected {% endif %}>{{ y }}</option>
                    {% empty %}
                    <option value="">Data Not Available</option>
                    {% endfor %}
                </select>
                <span class="error-text">Select Job type</span>
            </div>
            <div class="input-box active-grey">
                <label class="fieldlabels input-label" for="id_contact_person">Contact person</label>
                <select name="contact_person" class="input-1" id="id_contact_person" required>
                    <option value="">Select Contact Person</option>
                    {% for i in contact_person %}
                    <option value="{{i.id}}" {% if i.id == openingIDObj.contact_person.id %} selected {% endif %}>{{i.first_name}} {{i.last_name}}</option>
                    {% empty %}
                    <option value="">Data Not Available</option>
                    {% endfor %}
                </select>
                <span class="error-text">Select contact person</span>
            </div>
          </div>
        </div>
        <button type="submit" id="edit_opening-btn" class="action-button edit_opening-btn">Update</button>
        <button type="button" id="cancel-btn" data-redirect-url="{% url 'openings' %}" class="action-button-cancel">Cancel</button>
      </fieldset>
    </form>
</div>

<script src="{% static 'js/edit-opening.js' %}"></script>
{% endblock %}

akira_apps/adops/templates/adops/openings/openingsAppliedInfo.html
{% extends 'side_panel-navbar_dashboard.html' %}
{% load static %}

{% block analytics-text %}
<h1>Appl. Applied Info</h1>
<p>Manage your applied appl. <span class="fas fa-chart-line"></span> </p>
{% endblock %}

{% block manage-user_applied_openings %}

You applied for {{ appliedOpenings|length }} opening{{ appliedOpenings|length|pluralize }}

{% for i in appliedOpenings %}
<p>Job Name: {{ i.job }}</p>
<a href="{% url 'withdrawAppl' i.id %}">Withdraw the application</a>
<br>
<br>
{% endfor %}
<hr>

{% endblock %}

akira_apps/adops/templates/adops/openings/register_applicant.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <meta name="theme-color" content="#FFF"/>
    <meta name="description" content="AkirA is a kind of Learning Management System which can be accessible in all your devices Android, iOS, and desktop devices.">

    <link rel="stylesheet" href="{% static 'styles/dashboard.css' %}">
    
    <link href="{% static 'fontawesome/css/all.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome/css/fontawesome.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome/css/brands.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome/css/solid.css' %}" rel="stylesheet">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="apple-touch-icon" href="{% static 'images/AkirA-Logo V2.0.png' %}" type="image/icon type">
    <link rel="icon" href="{% static 'images/AkirA-Logo V2.0.png' %}" type="image/icon type">

    <script src="{% static "js/jquery.min.js" %}"></script>
    <title>Applicant Registration - AkirA</title>
</head>
<body>
    {% include 'messages.html' %}

    {% include 'check_internet_connection.html' %}

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="name_prefix">Name prefix</label>
        <select name="name_prefix" id="id_name_prefix">
            {% for x,y in name_prefix.fields.nameprefix.choices %}
            <option value="{{ x }}">{{ y }}</option>
            {% endfor %}
        </select>
        <br>
        <label for="firstname">First name</label>
        <input type="text" name="firstname" id="id_firstname" placeholder="First name" required>
        <br>
        <label for="lastname">Last name</label>
        <input type="text" name="lastname" id="id_lastname" placeholder="Last name" required>
        <br>
        <label for="username">Username</label>
        <input type="text" name="username" id="id_username" placeholder="Username" required>
        <br>
        <label for="password">Password</label>
        <input type="password" name="password" id="id_password" placeholder="Password" required>
        <br>
        <label for="confirm_password">Confirm password</label>
        <input type="password" name="confirm_password" id="id_confirm_password" placeholder="Confirm password" required>
        <br>
        <label for="email">Email</label>
        <input type="email" name="email" id="id_email" placeholder="Email" required>
        <br>
        <label for="phone">Phone number</label>
        <input type="phone" name="phone" id="id_phone" placeholder="Phone number" required>
        <br>

        <label for="date_of_birth">Date of birth</label>
        <input type="date" name="date_of_birth" id="id_date_of_birth" placeholder="Date of birth" required>
        <br>
        <label for="gender">Gender</label>
        <select name="gender" id="id_gender">
            {% for x,y in gender.fields.gender.choices %}
            <option value="{{ x }}">{{ y }}</option>
            {% endfor %}
        </select>
        <br>
        <label for="door_no">Door No.</label>
        <input type="text" name="door_no" id="id_door_no" placeholder="Door No." required>
        <br>
        <label for="zip_code">Zip code</label>
        <input type="text" name="zip_code" id="id_zip_code" placeholder="Zip code" required>
        <br>
        <label for="city">City name</label>
        <input type="text" name="city" id="id_city" placeholder="City name" required>
        <br>
        <label for="district">District name</label>
        <input type="text" name="district" id="id_district" placeholder="District name" required>
        <br>
        <label for="state">State name</label>
        <input type="text" name="state" id="id_state" placeholder="State name" required>
        <br>
        <label for="country">Country</label>
        <input type="text" name="country" id="id_country" placeholder="Country" required>
        <br>
        <label for="photo">Photo</label>
        <input type="file" name="photo" id="id_photo" required>
        <br>
        <label for="resume">Resume</label>
        <input type="file" name="resume" id="id_resume" required>
        <br>
        <p>By registering, You agree to our terms, condition and policies.</p>
        <br>
        <input type="submit" value="Register">
    </form>

    <script src="{% static 'js/dashboard.js' %}"></script>
</body>
</html>

akira_apps/adops/templates/adops/openings/verify_applicant_email.html
{% load i18n %}{% autoescape off %}
Hi {{ user.first_name }} {{ user.last_name }} @{{ user.username }},
Please click on the link to confirm your applicant registration with AkirA! Don't Share this Link to Anyone.
{{ protocol }}://{{ domain }}{% url 'confirm_applicant_email' uidb64=uid token=token %}
{% endautoescape %}